apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

patchesStrategicMerge:
  - deployments.yaml

images:
  - name: FW_BOOT_SAMPLES_IMAGE
    newName: <staging_ecr_repo>
